Repository cse110-sp24-group21/cse110-sp24-group21, pull requests merged in 2024-06, with the labels that each got.

#58 "Added new entry button, created TODO for disabling entry list to clo…
  src/assets/icons/delete_icon.png
  src/pages/entries.html
  src/scripts/entries.js
  src/styles/entries.css
Labels: enhancement, entries

#75 Fixed typo which resulted in dotW error
  src/scripts/calendar.js
Labels: bug

#74 Added CodeClimate Parameter Limit Change ADR
  specs/adrs/060424-CodeClimate-ArgCount-Config.md
  src/styles/calendar.css
Labels: documentation

#86 "Markdown styling in main page"
  src/styles/entries.css
Labels: enhancement, entries

#88 Style fix and fix minimize transition on every page
  src/components/navbar.js
  src/pages/calendar.html
  src/pages/entries.html
  src/pages/home.html
  src/styles/calendar.css
  src/styles/entries.css
  src/styles/home.css
  src/styles/tasks.css
Labels: enhancement

#103 Calendar display tasks
  src/pages/calendar.html
  src/pages/home.html
  src/scripts/calendar.js
  src/scripts/calendar_creation.js
  src/scripts/calendar_task_display.js
  src/styles/calendar.css
Labels: calendar

#112 fix add button entry on home page
  src/pages/home.html
  src/styles/home.css
Labels: bug

#115 calendar jsdocs documentation
  src/scripts/calendar.js
  src/scripts/calendar_creation.js
  src/scripts/calendar_task_display.js
Labels: documentation, calendar

#128 Progressive Web App (PWA) ADR
  specs/adrs/060724-PWA-Implementation.md
Labels: documentation, enhancement

#130 fix color when hover task at home page
  src/styles/home.css
Labels: enhancement

#134 final calendar e2e
  __tests__/e2e/calendar.e2e.js
Labels: enhancement, calendar
